#!/bin/bash

# DUNST notification
notify-send -i display "Display profile" "$AUTORANDR_CURRENT_PROFILE"

if [ "$AUTORANDR_CURRENT_PROFILE" == "docked-dorm" ]; then
          bspc monitor DP-3-2 -d 8 9 10
          bspc monitor DP-3-1 -d 4 5 6 7
          bspc monitor eDP-1 -d 1 2 3
	  $HOME/dotfiles/configs/polybar/ar_start.sh &
else
          bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10 11
	  bspc monitor DP-3-1 -d  
	  bspc monitor DP-3-2 -d
	  $HOME/dotfiles/configs/poylbar/ar_start.sh &
fi

#if [ "$AUTORANDR_CURRENT_PROFILE" == "mobile" ]; then
