keys:
  - &user_sylkos 8C04FBD390300C3AE3306CD98984B68ABBC5733D
  - &machine_endor age1qnjk7cwtzhl2seh70x4x79xxx9qmm0pzg9855gxqh72h48p9l4yqgqm4pz
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - pgp:
      - *user_sylkos
      age:
      - *machine_endor
