keys:
  - &user_sylkos 8C04FBD390300C3AE3306CD98984B68ABBC5733D
  - &machine_endor age1vu6vregvnwn4u3geu0nwl35p7wl77wp6z9k3thxu9m6pznvndvdqzdjl5p
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - pgp:
      - *user_sylkos
      age:
      - *machine_endor
