keys:
  - &user_sylkos 8C04FBD390300C3AE3306CD98984B68ABBC5733D
  - &machine_endor age103wevp6y689rgx5d3ca8hjqc54txcgqfh9u9q3jsneflhfathv7qmsrgch
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - pgp:
      - *user_sylkos
      age:
      - *machine_endor
