#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DVI-D-0 -d 1 2 3
bspc monitor DP-0 -d 4 5 6 7
bspc monitor HDMI-0 -d 8 9 0

bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle true
bspc config focus_follows_pointer true

# Polybar
$HOME/.config/polybar/sylkbar/preview.sh
nitrogen --restore
