#! /bin/sh
export _JAVA_AWT_WM_NONREPARENTING=1
export PATH=$PATH:/home/sylkos/.local/bin/
export PATH=$PATH:/home/sylkos/tools/eww/target/release/
xsetroot -cursor_name left_ptr

#autorandr -c
pgrep -x sxhkd > /dev/null || sxhkd &
picom -b & 
dunst -config ~/dotfiles/configs/dunst/dunstrc &
eww open bar

# Initial setup based on initial state
if [ "$(bspc query -M | wc -l)" -eq "3" ]; then
#  bspc monitor DP-3-2 -d 8 9 10	
#  bspc monitor DP-3-1 -d 4 5 6 7
#  bspc monitor eDP-1 -d 1 2 3 
  autorandr -c -f docked-dorm
else 
#  bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
  autorandr -c -f mobile
fi

bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config single_monocle true
bspc config focus_follows_pointer true

bspc config normal_border_color \#B19CD9
bspc config focused_border_color \#E98FC9
bspc config presel_feedback_color \#FFF758

bspc remove_disabled_monitors true
bspc remove_unplugged_monitors true
