#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
picom -b & 
dunst -config ~/dotfiles/configs/dunst/dunstrc &

# Initial setup based on initial state
if [ "$(bspc query -M | wc -l)" -eq "3" ]; then
  bspc monitor DP-3-1 -d 1 2 3	
  bspc monitor DP-3-2 -d 4 5 6 7
  bspc monitor eDP-1 -d 8 9 10 11

  rm $HOME/dotfiles/configs/polybar/m.ini
  printf "%s\n" "[m]" 'onitor=${env:MONITOR:DP-3-1}' > $HOME/dotfiles/configs/polybar/m.ini
else 
  bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10 11

  rm $HOME/dotfiles/configs/polybar/m.ini
  printf "%s\n" "[m]" 'onitor=${env:MONITOR:eDP-1}' > $HOME/dotfiles/configs/polybar/m.ini
fi

bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config single_monocle true
bspc config focus_follows_pointer true

bspc config normal_border_color \#B19CD9
bspc config focused_border_color \#E98FC9
bspc config presel_feedback_color \#FFF758

bspc remove_disabled_monitors true

# Polybar
$HOME/.config/polybar/start.sh &
$HOME/.config/polybar/systray.sh &

# Monitor config stuff
autorandr -c &
$HOME/dotfiles/config/bspwm/monitors.sh &
