#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom -b &
wmname LG3D &


# for via; may cause issues idk
lxqt-policykit-agent &

bspc monitor DVI-D-0 -d 1 2 3
bspc monitor DP-0 -d 4 5 6 7
bspc monitor HDMI-0 -d 8 9 0

bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config single_monocle true
bspc config focus_follows_pointer true

bspc config normal_border_color \#B19CD9
bspc config focused_border_color \#E98FC9
bspc config presel_feedback_color \#FFF758

# Polybar
$HOME/.config/polybar/sylkbar/preview.sh
nitrogen --restore
